### ISSUE TITLE
Update Form Module UI

### ISSUE THREAD

**Issue by chrissngn** [aaryatopiwala/TritonFoodShare#5]
Update form module with updated UI. Not including the google maps API or dietary tags backend (just leave a place holder on the UI side if it is not implemented yet).

**Comment by aaryatopiwala** [comment]
Additionally, the Form Module does not properly display My Events yet. The information collected by the form is displayed as a bullet point list on the bottom of the page.

**Comment by aaryatopiwala** [comment]
Created branch Update-Form-Module.
Updated Form module to take new input fields. UI of submitted forms assigned to @kevindo0720

**Comment by chrissngn** [comment]
Form Module has been updated with latest fields (dietary pref dropdown , location drop down), my event submission section, and link to submission display
